#!/usr/bin/env python

# Commands for automatic seatbelt application
# ("Seatbelts that automatically move into position around a vehicle occupant")

import sys

import seatbelt

seatbelt.serve(sys.argv[1])